### ISSUE TITLE
WHATWG migration

### ISSUE THREAD

**Issue by sisidovski** [whatwg/urlpattern#190]
As we discussed in https://github.com/whatwg/sg/issues/215, we're going to move URLPattern into WHATWG.

Here is the checklist that we should cover.

- [x] Reach WHATWG SG agreement: https://github.com/whatwg/sg/issues/215
- [x] Transfer repository from WICG to WHATWG
- [x] Create a logo: https://github.com/whatwg/whatwg.org/pull/427 and generally complete the checklist in https://github.com/whatwg/meta/blob/main/NEW-STANDARD.md
- [x] Update the document in this repository to account for this move
- [x] Add redirect for github.io URLs ([like this](https://github.com/WICG/wicg.github.io/blob/main/picture-in-picture/index.html)): https://github.com/WICG/wicg.github.io/pull/22

cc @domenic @jeremyroman

**Comment by domenic** [comment]
(Note that I edited the last item on the checklist to reflect how we _can_ redirect the github.io URLs.)

**Comment by domenic** [comment]
Given that we've broken https://wicg.github.io/urlpattern/, would one of the editors be willing to send a PR to add a redirect to the https://github.com/WICG/wicg.github.io repository?

Note that https://urlpattern.spec.whatwg.org/ doesn't display anything quite yet, but redirecting to that page is probably just as good as 404ing, and it's something we can do ahead of time.

**Comment by sisidovski** [comment]
I'm happy to take that task.

**Comment by sisidovski** [comment]
Sent https://github.com/WICG/wicg.github.io/pull/22

**Comment by domenic** [comment]
All done!

Some potential followup work in https://github.com/whatwg/urlpattern/issues/195.
