### ISSUE TITLE
"Hostname pattern is an IPv6 address" called with `null`

### ISSUE THREAD

**Issue by rubycon** [whatwg/urlpattern#209]
### What is the issue with the URL Pattern Standard?

The *hostname pattern is an IPv6 address* steps except a *pattern string* but in the [initialize](https://urlpattern.spec.whatwg.org/#urlpattern-initialize) steps it can directly be called with `null` when hostname isn't present in the argument passed to the constructor :

> 9. If the result running hostname pattern is an IPv6 address given processedInit["hostname"] is true, then...

The [*hostname pattern is an IPv6 address*](https://urlpattern.spec.whatwg.org/#hostname-pattern-is-an-ipv6-address) steps then fail to check its `null` input code point length:
> 1. If input’s code point length is less than 2, then return false.

This issue is related the `null` default value issue [discussed here](https://github.com/whatwg/urlpattern/issues/204#issuecomment-1891552179)

**Comment by jeremyroman** [comment]
Yes, this algorithm assumes that getting the value of a map returns null for absent entries, but that's not what map/get does (it asserts that the entry is present). Let me see what the simplest way to fix that is.
