### ISSUE TITLE
Anchor permanence for external URL Pattern integration?

### ISSUE THREAD

**Issue by pmeenan** [whatwg/urlpattern#231]
### What is the issue with the URL Pattern Standard?

As per https://whatwg.org/working-mode#anchors could we please make the following anchors permanent?

* https://urlpattern.spec.whatwg.org/#url-pattern-create
* https://urlpattern.spec.whatwg.org/#url-pattern-match
* https://urlpattern.spec.whatwg.org/#url-pattern-has-regexp-groups

These are used by the [compression dictionary](https://datatracker.ietf.org/doc/draft-ietf-httpbis-compression-dictionary/) spec.

**Comment by domenic** [comment]
FYI (this should be better documented somewhere for WHATWG standard editors) we can use https://speced.github.io/bikeshed/#metadata-required-ids to enforce this.
