### ISSUE TITLE
Suggestion to Add Translated Link for urlpattern (Simplified Chinese 简体中文)

### ISSUE THREAD

**Issue by JinDX** [whatwg/urlpattern#235]
### What is the issue with the URL Pattern Standard?

I have completed the translation of the URL Pattern specification into Simplified Chinese (简体中文). Here is the link to the translated document:

- [Translated version of the specification in Simplified Chinese](https://htmlspecs.com/urlpattern )

It would be helpful for international users if this link could be added to the official documentation.

Thank you for considering this request!

**Comment by sisidovski** [comment]
Thank you for making the translation! Added the link in #238.
